### ISSUE TITLE
impresion salidas (guias de estafeta)

### ISSUE THREAD

**Issue by kikoreyna** [abielmagudev/consolidated-laravel#14]
compadre lo escribo aqui para hacer testing de los issues y recordar ese tema quiza ya lo estas viendo, la impresion de la guia de estafeta tanto todo el consolidado, como lo filtrado

**Comment by abielmagudev** [comment]
Trabajando en ello compadre!

**Comment by kikoreyna** [comment]
> Trabajando en ello compadre!

Si me llego notificacion x correo

**Comment by abielmagudev** [comment]
Se resuelve con el tema de guias de impresion.

1. Crea la guia de impresion con las medidas y seleccion de informacion
2. Seleccionar una o varias entradas validas
3. Seleccionar  la guia de impresion para imprimir.
