### ISSUE TITLE
CONSOLIDADOS ABIERTOS NO AGREGA MAS ENTRADAS

### ISSUE THREAD

**Issue by kikoreyna** [abielmagudev/consolidated-laravel#22]
En la parte de Consolidados al crear nuevo consolidado te permite agregar nuevas entradas, pero una vez terminas de agregarlas ya no permite agregar mas aunque este abierto.

**Comment by abielmagudev** [comment]
Se resolvio que los consolidados abiertos puede agregar entradas, en cambio, el consolidado cerrado inhabilita la opcion de agregar y restringe agregar entradas.
